{"error": null, "issues": [{"address": 705, "code": "to.transfer(this.balance)", "debug": "SOLVER OUTPUT:\ncaller: 0x0\nstorage_0: 0x0\ncalldata_Wallet_0: 0x4ddaf8f200000000000000000000000000000000000000000000000000000000\ncalldatasize_Wallet: 0x4\ncallvalue: 0x0\n", "description": "In the function `migrateTo(address)` a non-zero amount of Ether is sent to an address taken from function arguments.\n\nThere is a check on storage index 0. This storage slot can be written to by calling the function `initWallet()`.", "filename": "/dataset/access_control/wallet_03_wrong_constructor.sol", "function": "migrateTo(address)", "lineno": 38, "title": "Ether send", "type": "Warning"}, {"address": 869, "code": "assert(balances[msg.sender] + msg.value > balances[msg.sender])", "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\ncallvalue: 0x0\ncalldata_Wallet_0: 0xd0e30db000000000000000000000000000000000000000000000000000000000\ncalldatasize_Wallet: 0x4\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/dataset/access_control/wallet_03_wrong_constructor.sol", "function": "deposit()", "lineno": 24, "title": "Exception state", "type": "Informational"}], "success": true}