CREATE2 instruction needs 4 arguments but 3 was given

Traceback (most recent call last):
  File "conkas.py", line 108, in main
    traces = sym_exec.execute()
  File "/conkas/sym_exec/symbolic_executor.py", line 51, in execute
    new_traces = self.__sym_exec_traces(traces_to_execute)
  File "/conkas/sym_exec/symbolic_executor.py", line 64, in __sym_exec_traces
    new_blocks = self.__sym_exec_block(block_to_analyse, trace.state)
  File "/conkas/sym_exec/symbolic_executor.py", line 93, in __sym_exec_block
    new_blocks = self.__sym_exec_instruction(instruction, state)
  File "/conkas/sym_exec/symbolic_executor.py", line 116, in __sym_exec_instruction
    return func(instruction, state)
  File "/conkas/sym_exec/instructions/closures.py", line 124, in inst_create2
    raise Exception
Exception
Analysing /data/0x0202B5014046b77EF98A870ab6EC78726136248B.hex...